import type { Metadata } from 'next'
import { Nunito, Reem_Kufi } from 'next/font/google'
import './globals.css'
import Providers from '@/providers/Providers'
import SignalRProvider from '@/providers/SignalRProvider'
import { auth } from '@/libs/auth/authOptions'

const geistNunito = Nunito({
  variable: '--font-geist-nunito',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap'
})

const fontReemKufi = Reem_Kufi({
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'STEMify Education',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico'
  }
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className={`${fontReemKufi.className}`}>
      <body className={`antialiased`}>
        <Providers>
          <main>
            <SignalRProvider>{children}</SignalRProvider>
          </main>
        </Providers>
      </body>
    </html>
  )
}
